name = "niconiahi"
compatibility_date = "2024-03-29"
pages_build_output_dir = "build/client"

[[d1_databases]]
binding = "DB"
database_name = "niconiahi-dev"
database_id = "10056191-9ec0-403b-8c4b-27a3dd18c836"
preview_database_id = "DB"
